Verifying the graph database in Neo4j for the BART system
Fundamentals of Data Engineering

# Modules and Packages

In [2]:
import neo4j

import csv

import math
import numpy as np
import pandas as pd

import psycopg2

# Code

In [3]:
driver = neo4j.GraphDatabase.driver(uri="neo4j://neo4j:7687", auth=("neo4j","ucb_mids_w205"))

In [4]:
session = driver.session(database="neo4j")

In [5]:
def my_neo4j_run_query_pandas(query, **kwargs):
    "run a query and return the results in a pandas dataframe"
    
    result = session.run(query, **kwargs)
    
    df = pd.DataFrame([r.values() for r in result], columns=result.keys())
    
    return df

In [6]:
def my_neo4j_shortest_path(from_station, to_station):
    "given a from station and to station, run and print the shortest path"
    
    query = "CALL gds.graph.drop('ds_graph', false)"
    session.run(query)

    query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
    session.run(query)

    query = """

    MATCH (source:Station {name: $source}), (target:Station {name: $target})
    CALL gds.shortestPath.dijkstra.stream(
        'ds_graph', 
        { sourceNode: source, 
          targetNode: target, 
          relationshipWeightProperty: 'weight'
        }
    )
    YIELD index, sourceNode, targetNode, totalCost, nodeIds, costs, path
    RETURN
        gds.util.asNode(sourceNode).name AS from,
        gds.util.asNode(targetNode).name AS to,
        totalCost,
        [nodeId IN nodeIds | gds.util.asNode(nodeId).name] AS nodes,
        costs
    ORDER BY index

    """

    result = session.run(query, source=from_station, target=to_station)
    
    for r in result:
        
        total_cost = int(r['totalCost'])
        
        print("\n--------------------------------")
        print("   Total Cost: ", total_cost)
        print("   Minutes: ", round(total_cost / 60.0,1))
        print("--------------------------------")
        
        nodes = r['nodes']
        costs = r['costs']
        
        i = 0
        previous = 0
        
        for n in nodes:
            
            print(n + ", " + str(int(costs[i]) - previous)  + ", " + str(int(costs[i])))
            
            previous = int(costs[i])
            i += 1

# Closeness Centrality

In [11]:
    
query = "CALL gds.graph.drop('ds_graph', false)"
session.run(query)

query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
session.run(query)

query = """

CALL gds.beta.closeness.stream('ds_graph')
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).name AS name, score as closeness
ORDER BY score DESC

"""

my_neo4j_run_query_pandas(query)

                    name  closeness
0            12th Street   0.147147
1           Lake Merritt   0.145833
2           West Oakland   0.145401
3            19th Street   0.141210
4              Fruitvale   0.137640
5            Embarcadero   0.136490
6              MacArthur   0.134986
7               Coliseum   0.129630
8      Montgomery Street   0.127937
9              Rockridge   0.124682
10                 Ashby   0.122195
11           San Leandro   0.121287
12         Powell Street   0.119804
13                Orinda   0.115294
14                   OAK   0.115023
15              Bay Fair   0.113426
16          Civic Center   0.112128
17     Downtown Berkeley   0.111111
18             Lafayette   0.106754
19   16th Street Mission   0.104925
20               Hayward   0.104701
21         Castro Valley   0.102941
22        North Berkeley   0.101449
23          Walnut Creek   0.098990
24   24th Street Mission   0.098196
25         South Hayward   0.096838
26           West Dublin   0.093870
27      El Cerrito Plaza   0.092979
28             Glen Park   0.091932
29         Pleasant Hill   0.091932
30            Union City   0.089744
31           Balboa Park   0.086116
32                Dublin   0.085965
33               Concord   0.085515
34  El Cerrito del Norte   0.085515
35               Fremont   0.083333
36             Daly City   0.080725
37         North Concord   0.079675
38              Richmond   0.078905
39          Warm Springs   0.077532
40                 Colma   0.075734
41             Pittsburg   0.074355
42              Milpitas   0.072271
43   South San Francisco   0.071118
44      Pittsburg Center   0.069504
45             Berryessa   0.067493
46             San Bruno   0.066849
47               Antioch   0.065073
48              Millbrae   0.062821
49                   SFO   0.062821

# Closeness Centrality
## Wasserman and Faust

In [10]:
    
query = "CALL gds.graph.drop('ds_graph', false)"
session.run(query)

query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
session.run(query)

query = """

CALL gds.beta.closeness.stream('ds_graph',
                               {useWassermanFaust: true}
                              )
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).name AS name, score as closeness
ORDER BY score DESC

"""

my_neo4j_run_query_pandas(query)

                    name  closeness
0            12th Street   0.147147
1           Lake Merritt   0.145833
2           West Oakland   0.145401
3            19th Street   0.141210
4              Fruitvale   0.137640
5            Embarcadero   0.136490
6              MacArthur   0.134986
7               Coliseum   0.129630
8      Montgomery Street   0.127937
9              Rockridge   0.124682
10                 Ashby   0.122195
11           San Leandro   0.121287
12         Powell Street   0.119804
13                Orinda   0.115294
14                   OAK   0.115023
15              Bay Fair   0.113426
16          Civic Center   0.112128
17     Downtown Berkeley   0.111111
18             Lafayette   0.106754
19   16th Street Mission   0.104925
20               Hayward   0.104701
21         Castro Valley   0.102941
22        North Berkeley   0.101449
23          Walnut Creek   0.098990
24   24th Street Mission   0.098196
25         South Hayward   0.096838
26           West Dublin   0.093870
27      El Cerrito Plaza   0.092979
28             Glen Park   0.091932
29         Pleasant Hill   0.091932
30            Union City   0.089744
31           Balboa Park   0.086116
32                Dublin   0.085965
33               Concord   0.085515
34  El Cerrito del Norte   0.085515
35               Fremont   0.083333
36             Daly City   0.080725
37         North Concord   0.079675
38              Richmond   0.078905
39          Warm Springs   0.077532
40                 Colma   0.075734
41             Pittsburg   0.074355
42              Milpitas   0.072271
43   South San Francisco   0.071118
44      Pittsburg Center   0.069504
45             Berryessa   0.067493
46             San Bruno   0.066849
47               Antioch   0.065073
48              Millbrae   0.062821
49                   SFO   0.062821

# Closeness Centrality
## Harmonic Centrality

In [9]:
    
query = "CALL gds.graph.drop('ds_graph', false)"
session.run(query)

query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
session.run(query)

query = """

CALL gds.alpha.closeness.harmonic.stream('ds_graph', {})
YIELD nodeId, centrality
RETURN gds.util.asNode(nodeId).name AS name, centrality as closeness
ORDER BY centrality DESC

"""

my_neo4j_run_query_pandas(query)

                    name  closeness
0            12th Street   0.233302
1           Lake Merritt   0.231867
2           West Oakland   0.228991
3              MacArthur   0.226052
4            19th Street   0.219525
5               Coliseum   0.216537
6              Fruitvale   0.214852
7               Bay Fair   0.209259
8            Embarcadero   0.204956
9            San Leandro   0.204085
10             Rockridge   0.201020
11                 Ashby   0.198599
12     Montgomery Street   0.192243
13                Orinda   0.187408
14               Hayward   0.186310
15         Powell Street   0.183524
16     Downtown Berkeley   0.182323
17         Castro Valley   0.179872
18             Lafayette   0.177701
19          Civic Center   0.176807
20         South Hayward   0.173498
21   16th Street Mission   0.171228
22          Walnut Creek   0.169799
23        North Berkeley   0.169367
24                   OAK   0.168257
25   24th Street Mission   0.166316
26            Union City   0.163598
27         Pleasant Hill   0.162728
28             Glen Park   0.161775
29           West Dublin   0.158443
30           Balboa Park   0.157391
31      El Cerrito Plaza   0.156995
32               Concord   0.155849
33               Fremont   0.154473
34             Daly City   0.153007
35         North Concord   0.148565
36                 Colma   0.148545
37          Warm Springs   0.144715
38   South San Francisco   0.144290
39             San Bruno   0.143603
40  El Cerrito del Norte   0.142626
41             Pittsburg   0.140030
42              Milpitas   0.132258
43                Dublin   0.130856
44      Pittsburg Center   0.128435
45              Millbrae   0.122641
46                   SFO   0.122641
47              Richmond   0.118996
48             Berryessa   0.110088
49               Antioch   0.106900

# Betweenness Centrality

In [8]:
    
query = "CALL gds.graph.drop('ds_graph', false)"
session.run(query)

query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
session.run(query)

query = """

CALL gds.betweenness.stream('ds_graph', {})
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).name AS name, score as betweenness
ORDER BY betweenness DESC

"""

my_neo4j_run_query_pandas(query)

                    name  betweenness
0              MacArthur       1176.0
1            12th Street       1116.0
2            19th Street       1088.0
3           Lake Merritt       1020.0
4              Fruitvale        980.0
5           West Oakland        980.0
6               Coliseum        960.0
7            Embarcadero        936.0
8      Montgomery Street        888.0
9          Powell Street        836.0
10           San Leandro        836.0
11              Bay Fair        822.0
12          Civic Center        780.0
13   16th Street Mission        720.0
14             Rockridge        720.0
15   24th Street Mission        656.0
16                Orinda        656.0
17             Glen Park        588.0
18             Lafayette        588.0
19           Balboa Park        516.0
20               Hayward        516.0
21          Walnut Creek        516.0
22                 Ashby        440.0
23             Daly City        440.0
24         Pleasant Hill        440.0
25         South Hayward        440.0
26                 Colma        360.0
27               Concord        360.0
28     Downtown Berkeley        360.0
29            Union City        360.0
30               Fremont        276.0
31        North Berkeley        276.0
32         North Concord        276.0
33   South San Francisco        276.0
34         Castro Valley        188.0
35      El Cerrito Plaza        188.0
36             Pittsburg        188.0
37             San Bruno        188.0
38          Warm Springs        188.0
39  El Cerrito del Norte         96.0
40              Milpitas         96.0
41      Pittsburg Center         96.0
42           West Dublin         96.0
43               Antioch          0.0
44             Berryessa          0.0
45                Dublin          0.0
46              Millbrae          0.0
47                   OAK          0.0
48              Richmond          0.0
49                   SFO          0.0

# Louvain Modularity

In [7]:
    
query = "CALL gds.graph.drop('ds_graph', false)"
session.run(query)

query = "CALL gds.graph.project('ds_graph', 'Station', 'LINK', {relationshipProperties: 'weight'})"
session.run(query)

query = """

CALL gds.louvain.stream('ds_graph', {includeIntermediateCommunities: true})
YIELD nodeId, communityId, intermediateCommunityIds
RETURN gds.util.asNode(nodeId).name AS name, communityId as community, intermediateCommunityIds as intermediate_community
ORDER BY community, name ASC

"""

my_neo4j_run_query_pandas(query)

                    name  community intermediate_community
0                  Ashby          2                [15, 2]
1      Downtown Berkeley          2                [15, 2]
2       El Cerrito Plaza          2                [38, 2]
3   El Cerrito del Norte          2                [38, 2]
4         North Berkeley          2                [15, 2]
5               Richmond          2                [38, 2]
6    16th Street Mission         10                [3, 10]
7    24th Street Mission         10                [3, 10]
8           Civic Center         10               [10, 10]
9              Glen Park         10                [3, 10]
10         Powell Street         10               [10, 10]
11           Balboa Park         14               [14, 14]
12                 Colma         14               [14, 14]
13             Daly City         14               [14, 14]
14              Millbrae         14               [42, 14]
15                   SFO         14               [42, 14]
16             San Bruno         14               [42, 14]
17   South San Francisco         14               [14, 14]
18              Bay Fair         23                [9, 23]
19         Castro Valley         23               [48, 23]
20              Coliseum         23               [32, 23]
21                Dublin         23               [48, 23]
22             Fruitvale         23               [32, 23]
23                   OAK         23               [32, 23]
24           San Leandro         23                [9, 23]
25           West Dublin         23               [48, 23]
26           12th Street         29               [25, 29]
27           Embarcadero         29               [29, 29]
28          Lake Merritt         29               [25, 29]
29     Montgomery Street         29               [29, 29]
30          West Oakland         29               [25, 29]
31               Antioch         31               [35, 31]
32               Concord         31               [31, 31]
33         North Concord         31               [31, 31]
34             Pittsburg         31               [35, 31]
35      Pittsburg Center         31               [35, 31]
36         Pleasant Hill         31               [46, 31]
37          Walnut Creek         31               [46, 31]
38             Berryessa         45               [28, 45]
39               Fremont         45               [45, 45]
40               Hayward         45               [23, 45]
41              Milpitas         45               [28, 45]
42         South Hayward         45               [23, 45]
43            Union City         45               [45, 45]
44          Warm Springs         45               [28, 45]
45           19th Street         46                [2, 46]
46             Lafayette         46               [33, 46]
47             MacArthur         46                [2, 46]
48                Orinda         46               [33, 46]
49             Rockridge         46               [33, 46]